# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: 'whitesource-ua-azdo-npm'

trigger:
- master

pool: KMT

- script: |
    echo Downloading WhiteSource Unified Agent
    curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
    if [[ "$(curl -sL https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar.sha256)" != "$(sha256sum wss-unified-agent.jar)" ]] ; then
      echo "Integrity Check Failed"
    else
      echo "Integrity Check Passed"
      echo Starting WhiteSource Scan
      java -jar wss-unified-agent.jar
    fi
  env:
    WS_APIKEY: $(B82cbe2ff08f46caab283e3ffdb7008b6bb4c957d159474bac53fc794e0b8a3e)
    WS_USERKEY: $(c4a2d2e6887747719f59d642de8733655c3b0c94f0974ef1a730399c9fd056f2)
    WS_WSS_URL: https://app-eu.whitesourcesoftware.com
    WS_PRODUCTNAME: AZDO_$(System.TeamProject)
    WS_PROJECTNAME: $(Build.Repository.Name)_$(Build.SourceBranchName)
  displayName: 'WhiteSource Scan'
