# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: KMT

steps: 
- task: SynopsysDetectTask@7
  inputs:
    BlackDuckService: 'HUBINT'
    DetectArguments: |
      set DETECT_LATEST_RELEASE_VERSION=7.0.0                                                                      
      powershell "[Net.ServicePointManager]::SecurityProtocol = 'tls12'; irm https://detect.synopsys.com/detect7.ps1?$(Get-Random) | iex; detect"
      --detect.timeout="300" --detect.project.name="NPMTest_azure" --detect.project.version.name="10.0"  --detect.detector.search.depth=10 --blackduck.trust.cert=true --detect.blackduck.signature.scanner.snippet.matching="SNIPPET_MATCHING" --detect.blackduck.signature.scanner.upload.source.mode="true" --detect.blackduck.signature.scanner.license.search="true" --detect.blackduck.signature.scanner.copyright.search="true" --detect.tools=SIGNATURE_SCAN --detect.tools=DETECTOR
    DetectVersion: '7.0.0'
