# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: KMT

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: SynopsysDetectTask@7
  inputs:
    DetectArguments: |
      --blackduck.url=https://foss-gsep.i.mercedes-benz.com 
      --blackduck.api.token=NzVkYzQzNjYtNjhmOC00ZTM3LWJhZDktM2I1YmE5MWRkZjRjOjM5MzdiODdlLTljY2ItNDM5ZS1hZTg2LTU3ODEyNjg1NjI2OQ==
      --detect.project.name="NPMTest_azure" 
      --detect.project.version.name="3.0"  
      --detect.detector.search.depth=10  
      --detect.timeout="300" 
      --blackduck.trust.cert=true 
      --detect.blackduck.signature.scanner.snippet.matching="SNIPPET_MATCHING" 
      --detect.blackduck.signature.scanner.upload.source.mode="true" 
      --detect.blackduck.signature.scanner.license.search="true" 
      --detect.blackduck.signature.scanner.copyright.search="true" 
      --detect.tools=SIGNATURE_SCAN 
      --detect.tools=DETECTOR
    DetectVersion: 'latest'