# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: KMT

- script: |
- task: SynopsysDetectTask@7
  inputs:
    BlackDuckService: 'BDHUB'
    DetectArguments: |
      --detect.project.name="AzureTest"
      --detect.project.version.name="1.0"
    DetectVersion: '7.0.0'
    
  steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'


